[package]
name = "do-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
sqlx = { version = "0.7.4", features = [
"postgres",
"runtime-tokio",
"tls-rustls",
] }
anyhow = "1.0.86"
dotenvy = "0.15.7"
